import asyncio
import smtplib
import time
from email.message import EmailMessage
from typing import Any, Mapping

from app.core.config import ConfigurationError, settings
from app.core.langfuse import observe, trace_tool_result
from app.core.logging import get_logger

logger = get_logger(__name__)


def _value(value: Any, default: str = "unknown") -> str:
    if value is None:
        return default
    text = getattr(value, "value", value)
    text = str(text).strip()
    return text or default


def _display_label(value: Any) -> str:
    return _value(value).replace("_", " ").replace("-", " ").title()


def _jira_line(jira_result: Mapping[str, Any] | None) -> str:
    if not jira_result:
        return "Jira ticket: not created"
    issue_key = _value(jira_result.get("issue_key"), "not created")
    issue_url = _value(jira_result.get("issue_url"), "")
    if issue_url:
        return f"Jira ticket: {issue_key} ({issue_url})"
    return f"Jira ticket: {issue_key}"


def _customer_lines(escalation_package: Mapping[str, Any]) -> list[str]:
    context = escalation_package.get("customer_context")
    if not isinstance(context, Mapping) or not context:
        return ["Customer/account context: not available"]
    return [
        f"Customer: {_value(context.get('company_name'))}",
        f"Customer ID: {_value(context.get('customer_id'))}",
        f"Account status: {_value(context.get('account_status'))}",
        f"Subscription/SLA: {_value(context.get('subscription_tier'))} / {_value(context.get('sla_level'))}",
        f"Region: {_value(context.get('region'))}",
    ]


def _incident_lines(escalation_package: Mapping[str, Any]) -> list[str]:
    investigation = escalation_package.get("incident_investigation")
    if not isinstance(investigation, Mapping) or not investigation:
        return ["Incident investigation: no correlated incident details available"]

    lines = [
        f"Active critical incident: {_value(investigation.get('active_critical_incident_correlated'), 'false')}",
        f"Incident evidence count: {len(investigation.get('matched_incidents') or [])}",
    ]
    for index, incident in enumerate((investigation.get("matched_incidents") or [])[:3], start=1):
        if isinstance(incident, Mapping):
            lines.append(
                "Incident "
                f"{index}: id={_value(incident.get('incident_id'))}, "
                f"severity={_value(incident.get('severity'))}, "
                f"status={_value(incident.get('resolution_status'))}, "
                f"region={_value(incident.get('affected_region'))}"
            )
    return lines


def _build_subject(state: Mapping[str, Any], escalation_package: Mapping[str, Any], jira_result: Mapping[str, Any] | None) -> str:
    target = _display_label(escalation_package.get("target") or state.get("escalation_target"))
    severity = _value(escalation_package.get("severity_priority") or escalation_package.get("severity"), "P0")
    issue_key = _value((jira_result or {}).get("issue_key"), "")
    suffix = f" | {issue_key}" if issue_key else ""
    return f"[ERIS][{severity}] Escalation to {target}{suffix}"


def _build_body(state: Mapping[str, Any], escalation_package: Mapping[str, Any], jira_result: Mapping[str, Any] | None) -> str:
    query = _value(escalation_package.get("query") or state.get("query"))
    target = _display_label(escalation_package.get("target") or state.get("escalation_target"))
    reason = _value(escalation_package.get("reason") or state.get("escalation_reason"))
    intent = _value(escalation_package.get("intent"))
    route = _value(escalation_package.get("route_decision"))
    severity = _value(escalation_package.get("severity_priority") or escalation_package.get("severity"))
    confidence = _value(escalation_package.get("confidence_score"))

    lines = [
        "ERIS escalation notification",
        "",
        "Summary",
        f"- Target team: {target}",
        f"- Severity: {severity}",
        f"- Reason: {reason}",
        f"- Original query: {query}",
        f"- Intent / route: {intent} / {route}",
        f"- Confidence: {confidence}",
        f"- {_jira_line(jira_result)}",
        "",
        "Customer/account context",
    ]
    lines.extend(f"- {line}" for line in _customer_lines(escalation_package))
    lines.extend(["", "Incident evidence"])
    lines.extend(f"- {line}" for line in _incident_lines(escalation_package))
    lines.extend(
        [
            "",
            "Required action",
            "- Review the Jira ticket and validate ownership.",
            "- Confirm customer/account and incident evidence before resolution or closure.",
            "- Update Jira with decision, mitigation, and next-owner notes.",
            "",
            "This message was generated by ERIS after an escalation decision.",
        ]
    )
    return "\n".join(lines)


def _send_email(subject: str, body: str, recipients: list[str]) -> None:
    settings.validate_for_escalation_email_mcp()

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = str(settings.escalation_email_from)
    message["To"] = ", ".join(recipients)
    message.set_content(body)

    with smtplib.SMTP(str(settings.smtp_host), int(settings.smtp_port), timeout=settings.smtp_timeout_seconds) as server:
        if settings.smtp_use_tls:
            server.starttls()
        if settings.smtp_username and settings.smtp_password:
            server.login(settings.smtp_username, settings.smtp_password)
        server.send_message(message)


@observe(name="email_mcp_tool", as_type="tool", capture_input=False, capture_output=False)
async def send_escalation_email(
    state: Mapping[str, Any],
    escalation_package: Mapping[str, Any],
    jira_result: Mapping[str, Any] | None,
) -> dict[str, Any]:
    """Notify the support team by email after an ERIS escalation."""

    started = time.perf_counter()
    result: dict[str, Any] = {
        "enabled": bool(settings.enable_escalation_email_mcp),
        "attempted": False,
        "sent": False,
        "recipients": settings.escalation_email_recipients,
        "subject": None,
        "error": None,
    }

    if not settings.enable_escalation_email_mcp:
        result["status"] = "disabled"
        trace_tool_result(tool_name="email_mcp_tool", question=str(state.get("query") or ""), result=result, started_at=started)
        return result

    if not settings.escalation_email_configured:
        result["status"] = "not_configured"
        result["error"] = "Escalation email is enabled but SMTP or recipient settings are incomplete."
        trace_tool_result(tool_name="email_mcp_tool", question=str(state.get("query") or ""), result=result, started_at=started)
        return result

    try:
        recipients = settings.escalation_email_recipients
        subject = _build_subject(state, escalation_package, jira_result)
        body = _build_body(state, escalation_package, jira_result)
        result.update({"attempted": True, "subject": subject})
        await asyncio.to_thread(_send_email, subject, body, recipients)
        result.update({"sent": True, "status": "sent"})
        logger.info("Escalation email sent recipients=%s subject=%s", recipients, subject)
    except ConfigurationError as exc:
        result.update({"status": "not_configured", "error": str(exc)})
        logger.warning("Escalation email configuration failed: %s", exc)
    except Exception as exc:
        result.update({"status": "failed", "error": str(exc)})
        logger.warning("Escalation email delivery failed: %s", exc)

    trace_tool_result(tool_name="email_mcp_tool", question=str(state.get("query") or ""), result=result, started_at=started)
    return result
